
# Synthetic dataset documentation ----

#' Synthetic raw ESSENCE-like ED visit data
#'
#' A fabricated dataset simulating a raw ESSENCE API data pull containing
#' common data quality issues: duplicate records of multiple types, non-ED
#' provider visits, out-of-state patient records, and `OTHER_REGION` entries.
#' All facility names, visit identifiers, patient identifiers, and geographic
#' values are entirely synthetic. No real patient or facility data are included.
#'
#' @format A data frame with approximately 190 rows and 18 columns:
#' \describe{
#'   \item{HospitalName}{Character. Synthetic facility name.}
#'   \item{Hospital}{Integer. Synthetic numeric facility identifier
#'     (`C_BioSense_Facility_ID` equivalent).}
#'   \item{FacilityType}{Character. ESSENCE facility type. Includes
#'     intentional misclassifications for two FSEDs (`"Urgent Care"`) to
#'     demonstrate [filter_care_setting()] correction logic.}
#'   \item{HospitalRegion}{Character. Facility ESSENCE Region in
#'     `{SITE}_{REGION}` format (e.g., `"KY_Jefferson"`).}
#'   \item{HospitalZip}{Character. Facility zip code.}
#'   \item{Visit_ID}{Character. Synthetic visit identifier, unique within
#'     a facility. Multiple rows with the same `HospitalName x Visit_ID`
#'     represent the duplicate patterns this package addresses.}
#'   \item{C_BioSense_ID}{Character. Synthetic BioSense record identifier.
#'     Multiple values per `Visit_ID` indicate `visit_date_change`
#'     duplication.}
#'   \item{C_Unique_Patient_ID}{Character. Synthetic patient identifier
#'     (MRN equivalent in Kentucky). Multiple values per `Visit_ID`
#'     indicate `pid_change` duplication.}
#'   \item{Date}{Date. Visit date.}
#'   \item{C_Visit_Date_Time}{POSIXct. Timestamp of the actual clinical
#'     encounter. Used by [link_encounters()] to chronologically order
#'     `.patient_class_sequence` when linking ED and direct-admit records.}
#'   \item{Arrived_Date_Time}{POSIXct. Timestamp when NSSP received the
#'     record. Use as `order_by` in [dedupe()] to retain the most recently
#'     transmitted version of each record.}
#'   \item{HasBeenE}{Integer. `1` if the visit has been classified as an
#'     emergency visit. All records in this dataset have `HasBeenE = 1`,
#'     consistent with a `HasBeenE = 1` filtered ESSENCE pull.}
#'   \item{HasBeenAdmitted}{Integer. `1` if the visit resulted in
#'     inpatient admission (discharge-disposition aware).}
#'   \item{Region}{Character. Patient ESSENCE Region of residence in
#'     `{SITE}_{REGION}` format. Includes out-of-state values
#'     (e.g., `"TN_Davidson"`) and `"OTHER_REGION"` entries to demonstrate
#'     [assign_treating_geography()].}
#'   \item{ZipCode}{Character. Patient zip code. May be `NA` for
#'     `OTHER_REGION` records.}
#'   \item{Sex}{Character. `"M"`, `"F"`, or `"U"` (unknown).}
#'   \item{C_Patient_Age}{Integer. Patient age in years.}
#' }
#'
#' @details
#' ## Duplicate patterns included
#' \describe{
#'   \item{`standard`}{5 visits with an extra row differing only in
#'     `Arrived_Date_Time` -- representing a record retransmission.}
#'   \item{`visit_date_change`}{3 visits with a second row carrying a new
#'     `C_BioSense_ID` and a `Date` advanced by 1 day -- representing a
#'     midnight-crossing visit where `Admit_Date_Time` was updated.}
#'   \item{`pid_change`}{2 visits with a second row carrying a different
#'     `C_Unique_Patient_ID` -- representing a corrected patient identifier.}
#'   \item{`visit_date_change+pid_change`}{1 visit exhibiting both
#'     mechanisms simultaneously.}
#' }
#'
#' ## Non-ED providers
#' 20 records from a `"Primary Care"` and a `"Medical Specialty"` facility
#' are included. These should be excluded by [filter_care_setting()].
#'
#' ## FSED misclassifications
#' `"Hillside FSED"` and `"Downtown Emergency Services"` are onboarded with
#' `FacilityType = "Urgent Care"`. These require correction via
#' `fix_facility_type_vector` in [filter_care_setting()].
#'
#' @source Entirely synthetic. Generated by `data-raw/generate_synthetic_data.R`.
#'   Column structure models an ESSENCE `va_er` (Patient Location, Full
#'   Details) pull, the data source against which `sysPrep`'s functions
#'   have been validated. Encounter linkage (`link_encounters()`) expects a
#'   supplemental inpatient pull structured as `va_hosp` (Facility Location,
#'   Full Details).
#' @seealso [essence_clean] for the processed version of this dataset;
#'   [dedupe()], [filter_care_setting()], [assign_treating_geography()].
"essence_raw"

#' Synthetic cleaned ESSENCE-like ED visit data
#'
#' The result of running `essence_raw` through the full `sysPrep` preprocessing
#' pipeline: deduplication, care setting filtering with FSED correction, and
#' treating geography assignment for out-of-state visits. Intended to
#' demonstrate the expected output of the package workflow and to serve as
#' a reference for function output structure.
#'
#' @format A data frame with approximately 160 rows and 21 columns. All
#'   column names are in snake_case (post [janitor::clean_names()]).
#' \describe{
#'   \item{hospital_name}{Character. Synthetic facility name.}
#'   \item{hospital}{Integer. Synthetic numeric facility identifier.}
#'   \item{facility_type}{Character. ESSENCE facility type. Non-ED
#'     providers have been removed; FSED corrections applied.}
#'   \item{hospital_region}{Character. Facility ESSENCE Region in
#'     `{SITE}_{REGION}` format.}
#'   \item{hospital_zip}{Character. Facility zip code.}
#'   \item{visit_id}{Character. Synthetic visit identifier, unique within
#'     a facility.}
#'   \item{c_bio_sense_id}{Character. Synthetic BioSense record identifier.
#'     One unique value per visit after deduplication.}
#'   \item{c_unique_patient_id}{Character. Synthetic patient identifier.}
#'   \item{date}{Date. Visit date.}
#'   \item{c_visit_date_time}{POSIXct. Timestamp of the actual clinical
#'     encounter.}
#'   \item{arrived_date_time}{POSIXct. NSSP record receipt timestamp.}
#'   \item{has_been_e}{Integer. `1` for all records (ED pull).}
#'   \item{has_been_admitted}{Integer. `1` if the visit resulted in
#'     inpatient admission.}
#'   \item{region}{Character. Patient ESSENCE Region of residence in
#'     `{SITE}_{REGION}` format. Out-of-state and `OTHER_REGION` visits have
#'     been reassigned to the treating facility's Region by
#'     [assign_treating_geography()].}
#'   \item{zip_code}{Character. Patient zip code (reassigned for
#'     out-of-state visits).}
#'   \item{sex}{Character. `"M"`, `"F"`, or `"U"`.}
#'   \item{c_patient_age}{Integer. Patient age in years.}
#'   \item{original_region}{Character. Pre-reassignment `Region` value,
#'     preserved when `preserve_original_geographies = TRUE`.}
#'   \item{original_zip_code}{Character. Pre-reassignment `ZipCode` value.}
#'   \item{.out_of_state}{Logical. `TRUE` for visits where `Region` and/or
#'     `ZipCode` were reassigned to treating facility geography.}
#' }
#'
#' @source Derived from [essence_raw] via
#'   `data-raw/generate_synthetic_data.R`.
#' @seealso [essence_raw] for the raw version; the Getting Started vignette
#'   for the full pipeline demonstration.
"essence_clean"
